### ISSUE TITLE
knowledgebase should use files from dataset not datasource

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#225]

**Comment by Abirdcfly** [comment]
```yaml
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: KnowledgeBase
metadata:
  name: knowledgebase-sample
  namespace: arcadia
spec:
  displayName: "测试 KnowledgeBase"
  description: "测试 KnowledgeBase"
  embedder:
    apiGroup: arcadia.kubeagi.k8s.com.cn/v1alpha1
    kind: Embedders
    name: zhipuai-embedders-sample
    namespace: arcadia
  vectorStore:
    apiGroup: arcadia.kubeagi.k8s.com.cn/v1alpha1
    kind: VectorStores
    name: chroma-sample
    namespace: arcadia
  versionedDataset: 
    versionedDataset:
      apiGroup: arcadia.kubeagi.k8s.com.cn
      kind: VersionedDataset
      name: dataset-playground-v1
      namespace: arcadia
    fileGroups:
      - datasource:
          apiGroup: arcadia.kubeagi.k8s.com.cn/v1alpha1
          kind: Datasources
          name: arcadia-local
        paths:
        - qa.csv
```
like this?
Because `VersionedDataset` may contain multiple `fileGroup`, the `knowledgebase` may use only some of these `filegroup`.
