### ISSUE TITLE
able to manage  llm service access info(CRD LLM)

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#28]
https://github.com/kubeagi/arcadia/blob/main/api/v1alpha1/llm_types.go

@Lanture1064 subtasks:

- [x] #34
- [x] impl the controller

**Comment by Lanture1064** [comment]
Assumed Field:
```yaml
metadata:
  name:
  namespace:
  label:
  annotation:
spec:
  modelName:
    description: 'modelName refers to the name of the model'
  modelVersion: v1
  modelSource:
    description: 'modelSource refers to the source of the llm, either "Local" as locally running model, or "Remote" as remote running model or commercial service'
  url:
    description: 'url refers to the url link of the llm'      
  auth:
    description: 'auth refers to the auth key to the llm, such as api key'
status:
  phase:
    description: 'phase marks the llm's running phase, either "running", "stopped", or "unavailable"'
  prompt:
    description: 'prompt is the last phrases sent to the llm, which should be an object from CRD Prompt'
  message:
    description: 'message is the returning result of last conversation'
  lastUpdateTime:
  retryCount:
parameters:
  description: 'parameters is the setting of the running model'
  maxTokens:
    description: 'maxTokens marks the limit of the input token quantity. 1 word averagely equals to 1.5 tokens.'
  temperature:
    description: 'temperature marks the 'randomness' of the model. Higher temperature, wilder models'
  otherParams:
    description: 'TODO: different model might have different params, such as fine-tuning params like top_K, plugin info, etc, which should be considered and dealt with'
```
