### ISSUE TITLE
Able to use our worker's llm/embedding service as 3rd provider

### ISSUE THREAD

**Issue by bjwswang** [kubeagi/arcadia#380]
For zhipuai & openai &dashscope, the model names are predefined.  Our worker now provides one model which is  named by using `CR Worker's ID`. We need to allow user configures the model names that this LLM/Embedder provides when user wants to add our woker's api service as  3rd provider.

## Details

Say we have two kubeagi clusters: Cluster-A and Cluster-B

We have deployed `qwen-7b-chat` model via Worker in Cluster-A  which have:
   - api url: http://cluster-a.com/v1
   - model id :  a3e0c8a6-101c-4000-a1cd-d523ff7f521d  (The worker's uid)

Now we want to add above model service to Cluster-B as a 3rd_party provider by:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: qwen-7b-chat-fs
type: Opaque
data:
  apiKey: "MTZlZDcxYzcwMDE0NGFiMjIyMmI5YmEwZDFhMTBhZTUuUTljWVZtWWxmdjlnZGtDeQ==" # replace this with your API key
---
---
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: LLM
metadata:
  name: qwen-7b-chat-fs
spec:
  displayName: 通义千问7B对话
  description: "这是一个对话模型服务,由Arcadia的Worker提供"
  type: "openai"
  models:
    - a3e0c8a6-101c-4000-a1cd-d523ff7f521d
  provider:
    endpoint:
      url: "http://cluster-a.com/v1"
      authSecret:
        kind: secret
        name: qwen-7b-chat-fs
      insecure: true
```
