### ISSUE TITLE
When the task fails, update the 'message' information in the dataset.

### ISSUE THREAD

**Issue by wangxinbiao** [kubeagi/arcadia#558]
If data processing task fails, update the 'message' information in the dataset for cr.

**Comment by 0xff-dev** [comment]
Example:

```yaml
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: VersionedDataset
metadata:
  generation: 1
  labels:
    arcadia.kubeagi.k8s.com.cn/owner: abcc
    arcadia.kubeagi.k8s.com.cn/version: v1
  name: abcc-v1
  namespace: abc
spec:
  creator: admin
  dataset:
    kind: Dataset
    name: abcc
    namespace: abc
  displayName: abcc-v1
  released: 0
  version: v1
status:
  conditions:
  - lastTransitionTime: "2023-12-29T07:24:25Z"
    message: sync msg test
    reason: FileSyncSuccess
    status: "True"
    type: Ready
  - lastTransitionTime: "2024-01-05T07:57:28Z"
    message: wrong message
    reason: process_fail
    status: "False"
    type: DataProcessing
  files:
  - kind: VersionedDataset
    name: inheritfrom-v1
    namespace: abc
```
