### ISSUE TITLE
🐛 Find the permissions needed for the command `gen_test_dataset`

### ISSUE THREAD

**Issue by 0xff-dev** [kubeagi/arcadia#690]
steps:

1. create a deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: permission
  namespace: rag-eval
  labels:
    app: permisson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: permission
  template:
    metadata:
      labels:
        app: permission
    spec:
      serviceAccountName: ragas-eval-sa
      containers:
      - name: nginx
        image: kubeagi/arcadia-eval
        command: 
        - "/bin/sh"
        args:
        - "-c"
        - "sleep 3600"
        ports:
        - containerPort: 80
```

2. Create a directory in pod

```
mkdir /tmp/abc
```

3. Add some test csv files under /tmp/abc

4.  exec the follow command

```shell
arctl -n=rag-eval eval gen_test_dataset --application=rag-qwen-test --input-dir=/tmp/abc --output=csv
```
This step will encounter missing permissions, and missing permissions should encounter the following output

```
panic: run node retriever-node: can't find the retriever in cluster: knowledgebaseretrievers.retriever.arcadia.kubeagi.k8s.com.cn "rag-test" is forbidden: User "system:serviceaccount:rag-eval:ragas-eval-sa" cannot get resource "knowledgebaseretrievers" in API group "retriever.arcadia.kubeagi.k8s.com.cn" in the namespace "rag-eval"
```

5. edit clusterrole `ragas-eval-clusterrole`

Edit the clusterrole to populate it with the required groups and resources and verbs.

6.  After the final command is executed successfully, just commit the contents of the clusterrole to the repository.
`deploy/charts/arcadia/templates/rag_job_rbac.yaml `
