### ISSUE TITLE
Add a CRD to convert audio/pdf to text

### ISSUE THREAD

**Issue by nkwangleiGIT** [kubeagi/arcadia#766]
Allow to define a CR and configure the input audio/pdf files (pdf, wav, mp3, etc ...), then the controller can transcribe pdf/audio to text file. Then we can use the text for QA or summary. 

Handle audio file:
```
apiVersion: converter.kubeagi.k8s.com.cn/v1alpha1
kind: Audio2Text
metadata:
  name: auto2text-converter1
  namespace: kubeagi-test
spec:
  files:
  - <audio file from MinIO>
status:
  condition: Processing
  result: <text from audio>
```
Handle pdf file:
```
apiVersion: converter.kubeagi.k8s.com.cn/v1alpha1
kind: Pdf2Text
metadata:
  name: pdf2text-converter1
  namespace: kubeagi-test
spec:
  files:
  - <pdf file from MinIO>
status:
  condition: Processing
  result: <text from pdf>
```

The converter can invoke the APIs or start a long-running job to handle the data. For other data processing, we can also follow the similar approach, and use these data process CRs to orchestrate LLM agent.
