### ISSUE TITLE
The path of the model file should be allowed to be customized

### ISSUE THREAD

**Issue by Abirdcfly** [kubeagi/arcadia#774]
for example `https://huggingface.co/maidalun1020/bce-reranker-base_v1` the model name `bce-embedding-base_v1` is not a valid kubernetes CRD name, we should change Model.name to `bce-embedding-base-v1`

IMO, the controller should use `metadata.annotations.arcadia.kubeagi.k8s.com.cn/full-path`
```yaml
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Model
metadata:
  annotations:
    arcadia.kubeagi.k8s.com.cn/full-path: kubeagi-system/model/bce-reranker-base_v1/
  labels:
    arcadia.kubeagi.k8s.com.cn/embedding: "true"
    arcadia.kubeagi.k8s.com.cn/llm: "false"
  name: bce-reranker-base-v1
  namespace: kubeagi-system
spec:
  description: bce-reranker-base_v1
  displayName: bce-reranker-base_v1
  types: embedding
```
cc @bjwswang @0xff-dev
